# Your Solution
# Your Solution
# version: '3'
services:

  book-catalog:
    image: book-catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
      - "8000:8000"
    environment:
      # - PORT=8081
      - DATABASE_URL=postgresql://task71_user:xqU9KDTeOlC5Wt5EmjWsMLg8IKUg9nfA@dpg-crmpc4dds78s73e9uom0-a.oregon-postgres.render.com/task71
    restart: "no"

  inventory-management:
    image: inventory-management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
     - "8001:8001"
    environment:
      # - PORT=8082
      - DATABASE_URL=postgresql://task71_user:xqU9KDTeOlC5Wt5EmjWsMLg8IKUg9nfA@dpg-crmpc4dds78s73e9uom0-a.oregon-postgres.render.com/task71
    restart: "no"
